dict = {
    'AI[UE]OON': ['aiueoon', '9.4'],                                     
    'Alexandrite': ['alexandrite', '9.9'],                               
    'Anokumene': ['anokumene', '9.2'],                                   
    'Antithese': ['antithese', '8.7'],                                   
    'Astral Tale': ['astraltale', '9.4'],                                
    'aterlbus': ['aterlbus', '10.5'],                                     
    'Auxesia': ['auxesia', '9.4'],                                       
    'Avant Raze': ['avantraze', '9.8'],                                  
    'Axium Crisis': ['axiumcrisis', '10.6'],                              
    'Babaroque': ['babaroque', '8.7'],                                   
    'Be There': ['bethere', '9.5'],                                      
    'Black Territory': ['blackterritory', '9.5'],                        
    'Blaster': ['blaster', '9.5'],                                       
    'Blossoms': ['blossoms', '7.6'],                                     
    'Bookmaker': ['bookmaker', '8.3'],                                   
    'Brand New World': ['brandnewworld', '7.9'],                         
    'Call My Name': ['callmyname', '8.8'],                               
    'Carmine Scythe': ['carminescythe', '9.6'],                          
    'Chelsea': ['chelsea', '8.6'],                                       
    'Chronostasis': ['chronostasis', '9.1'],                             
    'Clotho and the stargazer': ['clotho', '7'],                       
    'conflict': ['conflict', '10.3'],                                     
    'Corruption': ['corruption', '9.7'],                                 
    'CROSS+SOUL': ['crosssoul', '9.6'],                                  
    'Cyaegha': ['cyaegha', '10.8'],                                       
    'Cyanine': ['cyanine', '10.5'],                                       
    'Cybernecia Catharsis': ['cyberneciacatharsis', '9.8'],              
    'Dandelion': ['dandelion', '8.7'],                                   
    'Illegal Paradise': ['darakunosono', '9.8'],                         
    'DataErr0r': ['dataerror', '9.5'],                                   
    'Dement ~after legend~': ['dement', '7.9'],                          
    'Diode': ['diode', '8.2'],                                           
    'Dot to Dot': ['dottodot', '8.7'],                                   
    'Dreadnought': ['dreadnought', '9.7'],                               
    'Dream goes on': ['dreamgoeson', '7.5'],                             
    'Dreamin\' Attraction!!': ['dreaminattraction', '9.8'],               
    'dropdead': ['dropdead', '9.1'],                                     
    'DX Choseinou Full Metal Shojo': ['dxfullmetal', '9.7'],             
    'Empire of Winter': ['empireofwinter', '9.0'],                       
    'LunarOrbit -believe in the Espebranch road-': ['espebranch', '9.4'],
    'Essence of Twilight': ['essenceoftwilight', '9.0'],                 
    'Ether Strike': ['etherstrike', '10.2'],     
    'Evoltex': ['evoltex', '8.9'],                           
    'Fairytale': ['fairytale', '7.2'],                       
    'Fallensquare': ['fallensquare', '9.8'],                 
    'Filament': ['filament', '9.7'],                         
    'Flashback': ['flashback', '8.5'],                       
    'Flyburg and Endroll': ['flyburg', '9.2'],               
    'Fracture Ray': ['fractureray', '11.1'],                  
    'FREEF4LL': ['freefall', '8.7'],                         
    'Garakuta Doll Play': ['garakuta', '10.3'],               
    'Genesis': ['genesis', '8.4'],                           
    'GLORY：ROAD': ['gloryroad', '10.5'],                      
    'GOODTEK': ['goodtek', '9.4'],                           
    'Grievous Lady': ['grievouslady', '11.2'],                
    'Grimheart': ['grimheart', '8.6'],                       
    'guardina': ['guardina', '10.5'],                         
    'Halcyon': ['halcyon', '10.7'],                           
    'Hall of Mirrors': ['hallofmirrors', '8.2'],             
    'Harutopia ~Utopia of Spring~': ['harutopia', '8.6'],    
    'I\'ve heard it said': ['hearditsaid', '8.2'],            
    'Heavenly caress': ['heavenlycaress', '9.7'],            
    'Heavensdoor': ['heavensdoor', '10.0'],                   
    'Hikari': ['hikari', '8.3'],                             
    'Iconoclast': ['iconoclast', '9.4'],                     
    'Ignotus': ['ignotus', '9.7'],                           
    'Ikazuchi': ['ikazuchi', '10.4'],                         
    'Impure Bird': ['impurebird', '9.5'],                    
    'Infinity Heaven': ['infinityheaven', '7.6'],            
    'inkar-usi': ['inkarusi', '7.8'],                        
    'Journey': ['journey', '8.6'],                           
    'Kanagawa Cyber Culvert': ['kanagawa', '9.0'],           
    'Lethaeus': ['lethaeus', '9.5'],                         
    'Libertas': ['libertas', '9.2'],                         
    'Linear Accelerator': ['linearaccelerator', '9.5'],      
    'Lost Civilization': ['lostcivilization', '9.5'],        
    'Lucifer': ['lucifer', '8.3'],                           
    'Lumia': ['lumia', '8.5'],                               
    'Maze No.9': ['mazenine', '8.9'],                        
    'A Wondering Melody of Love': ['melodyoflove', '9.6'],   
    'memoryfactory.lzh': ['memoryfactory', '8.8'],           
    'Memory Forest': ['memoryforest', '9.8'],                
    'MERLIN': ['merlin', '8.6'],                             
    'Metallic Punisher': ['metallicpunisher', '10.3'], 
    'Mirzam': ['mirzam', '9.9'],                                           
    'Modelista': ['modelista', '10.0'],                                     
    'Monochrome Princess': ['monochromeprincess', '9.7'],                  
    'Moonheart': ['moonheart', '8.5'],                                     
    'Moonlight of Sand Castle': ['moonlightofsandcastle', '7'],          
    'Next to You': ['nexttoyou', '8.7'],                                   
    'Nhelv': ['nhelv', '9.8'],                                             
    'Nirv lucE': ['nirvluce', '10.3'],                                      
    'OMAKENO Stroke': ['omakeno', '9.6'],                                  
    'One Last Drive': ['onelastdrive', '8.1'],                             
    'Oracle': ['oracle', '9.3'],                                           
    'ouroboros -twin stroke of the end-': ['ouroboros', '10.6'],            
    'Paradise': ['paradise', '7.8'],                                       
    'Particle Arts': ['particlearts', '8.8'],                              
    'Party Vinyl': ['partyvinyl', '9.8'],                                  
    'Phantasia': ['phantasia', '9.2'],                                     
    'PRAGMATISM': ['pragmatism', '10.1'],                                   
    'Purgatorium': ['purgatorium', '8.4'],                                 
    'qualia -ideaesthesia-': ['qualia', '10.2'],                            
    'Quon': ['quon', '9.7'],                                               
    'Rabbit In The Black Room': ['rabbitintheblackroom', '8.5'],           
    'REconstruction': ['reconstruction', '8.7'],                           
    'Red and Blue': ['redandblue', '9.7'],                                 
    'Reinvent': ['reinvent', '8.6'],                                       
    'Relentless': ['relentless', '8.1'],                                   
    'ReviXy': ['revixy', '8.9'],                                           
    'Ringed Genesis': ['ringedgenesis', '10.7'],                            
    'Rise': ['rise', '7.7'],                                               
    'Romance Wars': ['romancewars', '7.4'],                                
    'Rugie': ['rugie', '9.0'],                                             
    'Sayonara Hatsukoi': ['sayonarahatsukoi', '6.5'],                      
    'Scarlet Lance': ['scarletlance', '10.3'],                              
    'Senkyou': ['senkyou', '8.8'],                                         
    'Shades of Light in a Transcendent Realm': ['shadesoflight', '8.4'],   
    'Sheriruth': ['sheriruth', '10.6'],                                     
    'Silent Rush': ['silentrush', '8.4'],                                  
    'Singularity': ['singularity', '10.4'],                                 
    'Snow White': ['snowwhite', '8.6'],                                    
    'Solitary Dream': ['solitarydream', '8.4'],
    'SOUNDWiTCH': ['soundwitch', '9.9'],
    'Specta': ['specta', '9.5'],
    'STAGER (ALL STAGE CLEAR)': ['stager', '9.2'],
    'Strongholds': ['strongholds', '9.1'],
    'Sulfur': ['sulfur', '9.8'],
    'Suomi': ['suomi', '7.7'],
    'SUPERNOVA': ['supernova', '9.7'],
    'Surrender': ['surrender', '8.8'],
    'Syro': ['syro', '9.5'],
    'The Message': ['themessage', '9.7'],
    'Tie me down gently': ['tiemedowngently', '8.4'],
    'Tiferet': ['tiferet', '10.5'],
    'trappola bewitching': ['trappola', '10.0'],
    'Tutorial': ['tutorial', '0'],
    'Valhalla:0': ['valhallazero', '10.5'],
    'VECTOR': ['vector', '9.5'],
    'Vexaria': ['vexaria', '7.4'],
    'Vicious Heroism': ['viciousheroism', '10.0'],
    'Vindication': ['vindication', '9.6'],
    'cry of viyella': ['viyella', '8.7'],
    'World Vanquisher': ['worldvanquisher', '10.6'],
    'Your voice so...': ['yourvoiceso', '9.4'],
    'Yosakura Fubuki': ['yozakurafubuki', '10.6']                                                            
}